[tools."github:twpayne/chezmoi"]
version = "2.69.3"
[tools."github:twpayne/chezmoi".platforms]
linux-x64 = { asset_pattern = "chezmoi_{version}_linux-musl_amd64.tar.gz" }

[tasks.apply-dotfiles]
run = "chezmoi apply -S ."

[tasks.bump-tools]
run = "mise upgrade --bump --cd dot_config/mise/conf.d"

[tasks.use-starship]
run = '''
cp assets/starship/tokyo.toml dot_config/starship.toml
'''
