[tools]
carapace = "1.5"
atuin = "18.11.0"
zoxide = "0.9.8"
starship = "1.24.2"
yazi = "26.1.4"
zellij = "0.43.1"
direnv = "2.37.1"
bat = "0.26.1"
fzf = "0.67.0"
eza = "0.23.4"
ripgrep = "15.1.0"
fd = "10.3.0"
dust = "1.2.4"
jq = "1.8.1"
yq = "4.50.1"
gitui = "0.28.0"
"github:nushell/nushell" = { version = "0.110.0", asset_pattern = "nu-*-x86_64-unknown-linux-musl.tar.gz" }
