[tools]
carapace = "1.6"
atuin = "18.11.0"
zoxide = "0.9.9"
starship = "1.24.2"
yazi = "26.1.22"
zellij = "0.43.1"
direnv = "2.37.1"
bat = "0.26.1"
fzf = "0.67.0"
eza = "0.23.4"
ripgrep = "15.1.0"
fd = "10.3.0"
dust = "1.2.4"
jq = "1.8.1"
yq = "4.52.2"
gitui = "0.28.0"
